version: '3'

services:
  colab-runtime:
    image: us-docker.pkg.dev/colab-images/public/runtime
    container_name: colab-runtime-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/maheidem/docker/colab/content:/content
      - /home/maheidem/docker/colab/temp:/tmp
    ports:
      - "9000:8080"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    storage_opt:
      size: 200G  # Specify the storage size
