version: '3'

services:
  debian-bash:
    image: dockerdevenvproject:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "2022:22"
      - "8888:8080"